### ISSUE TITLE
pushbots-cli doesnt run on Windows 8.1

### ISSUE THREAD

**Issue by jacboy** [pushbots/pushbots-cli#1]
I´ve tried to install pushbots-cli to Windows 8.1, but it failed with fatal errors....fresh npm install, 10mins old :/

**Comment by amrsobhy** [comment]
In order to install pushbots cli on widnows you must first: 

Install python: http://www.python.org/getit/windows/
Install Microsoft Visual Studio C++ 2012 Express version: http://go.microsoft.com/?linkid=9816758
Install node-gyp: npm install -g node-gyp
